# Kotlin
kotlinVersion=1.9.22

# Cucumber
cucumberVersion=7.14.0

# Allure
allureVersion=2.24.0

# Selenium
seleniumVersion=4.18.1

# WebDriverManager
webdrivermanagerVersion=5.7.0

# JUnit Platform
junitPlatformVersion=1.10.2
junitJupiterVersion=5.10.2

# Logging
slf4jVersion=2.0.9
logbackVersion=1.4.14